# Generated by Django 3.2 on 2021-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=255)),
                ('to_currency', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
